version: '3.1'
language: en
pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: '[OOV]'
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 25
  learning_rate: 0.001
- name: FallbackClassifier
  threshold: 0.6
  ambiguity_threshold: 0.1
